FIX TYPOOOOOOOO
touwoyimuli/QtExamples pull request #4
Opened 2020-08-24 08:03 UTC by ChungZH

强迫症忍不住就 fix 了一堆 typo，ya 鸭鸭 :smiley_cat:

2020-08-24 08:04 UTC, ChungZH commented on README.md
> +- `qt` 中 lambda 表达式
:thinking: 这里感觉应该是 lambda，又或者是我太菜了吧（

2020-08-24 08:04 UTC, ChungZH commented on README.md
> +- [如何给上游 Qt 提交 Bug 反馈和贡献代码 PATCH？](https://xmuli.blog.csdn.net/article/details/107220867)
这里也是感觉应该是 PATCH :thinking:

2020-08-24 08:04 UTC, ChungZH commented on README.md
> +  - [应用软件在「uos20和 MaOS10.14下」显示应用不同的QStyle「即：所有控件的样式换肤」](https://blog.csdn.net/qq_33154343/article/details/104305154)
还有这里就肯定是 uos 啦（

2020-10-20 13:13 UTC, xmuli commented
如果有空的话, 可以 `rebase` 一下, 然后我合并一下(之前搁置就忘记了, 怪不好意思的~)

2020-10-24 03:41 UTC, xmuli requested changes
需要 rebase 一下

2020-10-24 07:49 UTC, closed without merging

2020-10-24 07:50 UTC, ChungZH commented
我重新搞一次吧。。